title: APIM Labs
description: Self-paced hands-on labs to discover the APIM7.7 product
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
classes: wide
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
